# Build
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/smart-api-840b7/positional-algo-repo/positional-api-image:tag1', '.' ]

# Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 
           'us-central1-docker.pkg.dev/smart-api-840b7/positional-algo-repo/positional-api-image:tag1']  
        
images:
- 'us-central1-docker.pkg.dev/smart-api-840b7/positional-algo-repo/positional-api-image:tag1'
